# Generated by Django 5.1.2 on 2025-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='model_name',
            field=models.TextField(default='model', max_length=255),
            preserve_default=False,
        ),
    ]
