name: Django CI

on:
  push:
    branches:
      - main
  pull_request: #for all PR branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: SOC
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Pull MATLAB Docker image
        run: |
          docker pull mathworks/matlab:r2025a

      - name: Run MATLAB with Docker and install dependencies
        run: |
          docker run --rm -v $(pwd):/workspace mathworks/matlab:r2025a /bin/bash -c "cd /workspace && pip install -r src/requirements.txt"

      - name: Run migrations
        env:
          DATABASE_URL: postgres://root:password@localhost:5432/SOC
        run: |
          python src/webserver/webserver/manage.py migrate

      - name: Run unit tests
        env:
          DATABASE_URL: postgres://root:password@localhost:5432/SOC
        run: |
          python src/webserver/webserver/manage.py test
