name: Build latex files

on:
  push:
    paths:
      - "**/*.tex"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kjarosh/latex:2024.4

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile new or updated latex files
        run: |
          CHANGED_LATEX_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.tex$')
          echo "Changed files: $CHANGED_LATEX_FILES"
          for FILE in $CHANGED_LATEX_FILES; do
            echo "Compiling $FILE"
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$FILE" && echo "$FILE compiled successfully" || echo "Failed to compile $FILE"
          done
