name: Build latex files

on:
  push:
    paths:
      - "**/*.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache latex
        id: cache-latex
        uses: actions/cache@v3
        with:
          path: ~/.texfile
          key: ${{ runner.os }}-latex-texfile
          restore-keys: |
            ${{ runner.os }}-latex-

      - name: Install latex if not cached
        run: |
          if steps.cache-latex.outputs.cache-hit == "true" ]; then
            echo "Cache found. Skip latex installation"
          else
            echo "Installing LaTeX..."
            sudo apt-get update
            sudo apt-get install -y texlive-full
          fi

      - name: Compile new or updated latex files
        run: |
          CHANGED_LATEX_FILES=$(git diff --name-only origin/main HEAD | grep '\.tex$')
          echo "Changed files: $CHANGED_LATEX_FILES"
          for FILE in $CHANGED_LATEX_FILES; do
            echo "Compiling $FILE"
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$FILE" && echo "$FILE compiled successfully" || echo "Failed to compile $FILE"
          done
