name: Build latex files

on:
  push:
    paths:
      - "**/*.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache latex
        id: cache-latex
        uses: actions/cache@v3
        with:
          path: ~/.texfile
          key: ${{ runner.os }}-latex-texfile
          restore-keys: |
            ${{ runner.os }}-latex-

      - name: Install latex if not cached
        run: |
          if steps.cache-latex.outputs.cache-hit == "true"; then
            echo "Cache found. Skip latex installation"
          else
            echo "Installing LaTeX..."
            sudo apt-get update
            sudo apt-get install -y texlive-full latexmk
          fi

      - name: Compile new or updated latex files
        run: |
          git diff --name-only HEAD^ HEAD | grep '\.tex$' > updated_tex_files.txt
          while read -r file; do
            echo "Compiling $file"
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$file" || exit 1
          done < updated_tex_files.txt
